name: CI-tests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: targets
        required: true
        default: All tests
        type: choice
        options:
          - All tests
          - Api
          - Ui
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkaout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: All tests
        if: "github.event.inputs.deployment_target == 'All tests'"
        run: pytest
      - name: Api
        if: "github.event.inputs.deployment_target == 'Api'"
        run: pytest tests/api
      - name: Ui
        if: "github.event.inputs.deployment_target == 'Ui'"
        run: pytest test/ui
    
